
# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#

version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image:  google/cloud-sdk
    steps:
      - checkout
      - run:
          name: run tests
          command: |
            echo "-----start test:"
            python simple_test.py
            echo "-----end test"
      - run:
          name: run config
          command: |    
            echo "----run gcp config"
            
            echo $GCLOUD_SERVICE_KEY | base64 --decode --ignore-garbage > ./gcloud-service-key.json
            gcloud auth activate-service-account --key-file=./gcloud-service-key.json
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
            gcloud --quiet container clusters get-credentials ${GOOGLE_CLUSTER_NAME}
            echo "-----end config"
            
      - run:
         name:prepare to deploy
         command:|
          
           docker build -t gcr.io/$GOOGLE_PROJECT_ID/hello-circleci-app:v1 .
           gcloud docker -- push gcr.io/${GOOGLE_PROJECT_ID}/hello-circleci-app:v1
           gcloud container clusters create hello-circleci-cluster --num-nodes=2
           kubectl run hello-circleci-web --image=gcr.io/${GOOGLE_PROJECT_ID}/hello-circleci-app:v1 --port 8080
           kubectl expose deployment hello-circleci-web --type=LoadBalancer --port 80 --target-port 8080
           kubectl scale deployment hello-circleci-web --replicas=2
          

            
  deploy:
    docker:
      - image: google/cloud-sdk
    steps:
      - run:
          name: run config
          command: |    
            
            echo $GCLOUD_SERVICE_KEY | base64 --decode --ignore-garbage > ./gcloud-service-key.json
            gcloud auth activate-service-account --key-file=./gcloud-service-key.json
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
            gcloud --quiet container clusters get-credentials ${GOOGLE_CLUSTER_NAME}

      - run:
          name: Decode and Store Service Account
          command: |
            
            docker build -t gcr.io/${GOOGLE_PROJECT_ID}/hello-circleci-app:v2 .
            gcloud docker -- push gcr.io/${GOOGLE_PROJECT_ID}/hello-circleci-app:v2
            kubectl set image deployment/hello-circleci-web hello-circleci-web=gcr.io/${GOOGLE_PROJECT_ID}/hello-app:v2
            kubectl expose deployment hello-circleci-web --type=LoadBalancer --port 80 --target-port 8080
           

        
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
